apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: travelbee-api-hpa
  namespace: travelbee-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: travelbee-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: travelbee-realtime-hpa
  namespace: travelbee-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: travelbee-realtime
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
