apiVersion: v1
kind: ServiceAccount
metadata:
  name: travelbee-sa
  namespace: travelbee-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: travelbee-pod-manager
  namespace: travelbee-prod
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: travelbee-rbac-binding
  namespace: travelbee-prod
subjects:
- kind: ServiceAccount
  name: travelbee-sa
  namespace: travelbee-prod
roleRef:
  kind: Role
  name: travelbee-pod-manager
  apiGroup: rbac.authorization.k8s.io
