apiVersion: v1
kind: Secret
metadata:
  name: travelbee-secrets
  namespace: travelbee-prod
type: Opaque
data:
  # Base64 encoded placeholders
  # JWT_SECRET: "super_secure_travelbee_jwt_secret_key_2026"
  JWT_SECRET: "c3VwZXJfc2VjdXJlX3RyYXZlbGJlZV9qd3Rfc2VjcmV0X2tleV8yMDI2"
  # MAPS_API_KEY: "dummy_google_maps_api_key_secret"
  MAPS_API_KEY: "ZHVtbXlfZ29vZ2xlX21hcHNfYXBpX2tleV9zZWNyZXQ="
